services:
  app:
    image: ${DOCKER_COMPOSE_IMAGE_NAME}
    container_name: "${NAME}"
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${DOCKER_PORT}:80"
    networks:
      - default
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "${AWS_LOG_GROUP}"
        awslogs-create-group: "true"
        tag: "{{.Name}}"

  postgresql:
    image: "postgres:alpine"
    container_name: "${NAME}-postgresql"
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=${DATABASE_NAME}"
    volumes:
      - postgresql:/data/postgres
    networks:
      - default
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -h localhost -p 5432" ]
      start_period: 5s
      interval: 10s
      timeout: 5s

networks:
  default:
    name: "${NAME}-backend"
    driver: bridge

volumes:
  postgresql:
    name: "${NAME}-postgresql"
